name: Android CI

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EverythingSuckz/github-telegram-notify@main
        continue-on-error: true
        with:
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: -1002327390277
          topic_id: 2
          
  build_debug_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          
  send_debug_apk:
    runs-on: ubuntu-latest
    needs: build_debug_apk
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-debug
      - run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
            -F chat_id="-1002327390277" \
            -F message_thread_id="2" \
            -F document=@"app-debug.apk" \
            -F caption="APK de debug gerado por ${{ github.actor }}"
