name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Check if gradlew exists
      id: check_gradlew
      run: |
        if [ ! -f gradlew ]; then
          echo "gradlew not found, generating wrapper..."
          gradle wrapper
        else
          echo "gradlew found."
        fi

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug APK with Gradle
      run: ./gradlew assembleDebug

    - name: Archive debug APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
